on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - closed

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:      
      - name: check pull request format
        run: |
          curl -X POST \
            'https://app.asana.com/api/1.0/tasks/1203113430774142/stories' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.ASANA_SECRET }}' \
            --data-raw '{
            "data": {
              "text": "${{github.event.pull_request.html_url}}"
            }
          }'
